- name: Demo on filters
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT

    - name: Print No Of Users Logged In
      ansible.builtin.debug:
        msg: "{{ OUT.stdout | split',' }}"